import Head from 'next/head';
import Image from 'next/image';
import Button from '@mui/material/Button';
import axios from 'axios';
import { useEffect } from 'react';
import { useState } from 'react';
import ItemList from '@/components/ItemList';
import { CircularProgress } from '@mui/material';

const Home = () => {
  const [list, setList] = useState([]);
  const [isLoading, setIsLoading] = useState(true);

  const API_URL =
    'https://ddragon.leagueoflegends.com/cdn/12.9.1/data/ko_KR/champion.json';

  const getData = () => {
    axios.get(API_URL).then((res) => {
      setList(res.data.data);
      setIsLoading(false);
    });
  };

  useEffect(() => {
    getData();
  }, []);

  return (
    <>
      <Head>
        <title>오피쩜지지</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isLoading ? <CircularProgress /> : <ItemList list={list} />}
    </>
  );
};

export default Home;
